name: Build CI wheels

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        cibw_archs_linux: ["auto"]
        cibw_numpy_version: [1.16]
        include:
          - os: ubuntu-18.04
            cibw_archs_linux: "aarch64"
            cibw_numpy_version: 1.19.3

    steps:
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Copy setup.cfg to configure wheel
        run: |
          cp setup.cfg.template setup.cfg

      - name: ENV Variables
        run: |
          echo "NUMPY=${{ matrix.cibw_numpy_version }}"
          echo "ARCH=${{ matrix.cibw_archs_linux }}"

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install certifi numpy==1.19.3
          MPL_DISABLE_FH4: "yes"
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs_linux }}

      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "cp35-* cp36-* cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install certifi numpy==${{ matrix.cibw_numpy_version }}
          MPL_DISABLE_FH4: "yes"
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs_linux }}

      - name: Build wheels for CPython 3.6
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp36-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install certifi numpy==${{ matrix.cibw_numpy_version }}
          MPL_DISABLE_FH4: "yes"
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs_linux }}
        if: >
          startsWith(github.ref, 'refs/heads/v3.3') ||
          startsWith(github.ref, 'refs/tags/v3.3')

      - name: Build wheels for PyPy
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "pp3?-*"
          CIBW_BEFORE_BUILD: pip install certifi numpy==${{ matrix.cibw_numpy_version }}
          CIBW_ARCHS_LINUX: auto aarch64
        if: >
          runner.os != 'Windows' && (
          startsWith(github.ref, 'refs/heads/v3.3') ||
          startsWith(github.ref, 'refs/tags/v3.3') )

      - name: Validate that LICENSE files are included in wheels
        run: |
          python ./ci/check_wheel_licenses.py

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl
